Import('env')
Import('build_target')

env.Object(target='#/' + build_target + 'scene-scene', source=['scene.cpp'])
env.Object(target='#/' + build_target + 'scene-sprite_2d', source=['sprite_2d.cpp'])
env.Object(target='#/' + build_target + 'scene-color_rect', source=['color_rect.cpp'])
env.Object(target='#/' + build_target + 'scene-startup_scene', source=['startup_scene.cpp'])
env.Object(target='#/' + build_target + 'scene-audio_stream_player', source=['audio_stream_player.cpp'])
